import { Metadata } from "next";
import "./globals.css";
import MainLayoutContext from "./context/MainLayoutContext";


export const metadata: Metadata = {
  title: "Faeze Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <MainLayoutContext>
          {children}
        </MainLayoutContext>
      </body>
    </html>
  );
}
